/**
 * Agent State Schema for LangGraph Coordinator
 *
 * Defines the global state that flows through the coordinator workflow.
 * Uses LangGraph's Annotation system for type-safe state management.
 */

import { Annotation, MessagesAnnotation } from "@langchain/langgraph";
import type { Intent, StructuredData, Suggestion } from "./types";

/**
 * Agent State for the Coordinator workflow
 *
 * This state flows through all nodes in the coordinator graph:
 * 1. Coordinator Node (classifies intent)
 * 2. Agent Nodes (search_team, auditor, comparator, etc.)
 * 3. Synthesizer Node (generates summary and suggestions)
 */
export const AgentState = Annotation.Root({
  /**
   * Messages in the conversation
   * Inherited from MessagesAnnotation for LangGraph compatibility
   */
  ...MessagesAnnotation.spec,

  /**
   * Classified intent from coordinator
   * Determines which agent to route to
   */
  intent: Annotation<Intent | undefined>({
    reducer: (_, value) => value,
    default: () => undefined,
  }),

  /**
   * Structured data returned by agents
   * Union type for type safety
   */
  structuredData: Annotation<StructuredData>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  /**
   * Conversation ID for tracking and history
   */
  conversationId: Annotation<string>({
    reducer: (_, value) => value,
    default: () => "",
  }),

  /**
   * Context summary for compression
   * Used when conversation history grows large
   */
  contextSummary: Annotation<string | undefined>({
    reducer: (_, value) => value,
    default: () => undefined,
  }),

  /**
   * Follow-up suggestions generated by synthesizer
   */
  suggestions: Annotation<Suggestion[] | undefined>({
    reducer: (_, value) => value,
    default: () => undefined,
  }),

  /**
   * Error tracking
   */
  error: Annotation<string | undefined>({
    reducer: (_, value) => value,
    default: () => undefined,
  }),

  /**
   * Execution metadata
   */
  metadata: Annotation<Record<string, unknown>>({
    reducer: (current, value) => ({ ...current, ...value }),
    default: () => ({}),
  }),
});

/**
 * Type inference for AgentState
 * Use this type when working with state in nodes
 */
export type AgentStateType = typeof AgentState.State;
